// Written by Jürgen Moßgraber - mossgrabers.de
//            Michael Schmalle - teotigraphix.com
// (c) 2014
// Licensed under GPLv3 - http://www.gnu.org/licenses/gpl.html

// Push Colors

// First row colors
var PUSH_COLOR_BLACK            = 0;
var PUSH_COLOR_RED_LO           = 1;
var PUSH_COLOR_RED_LO_SBLINK    = 2;
var PUSH_COLOR_RED_LO_FBLINK    = 3;
var PUSH_COLOR_RED_HI           = 4;
var PUSH_COLOR_RED_HI_SBLINK    = 5;
var PUSH_COLOR_RED_HI_FBLINK    = 6;
var PUSH_COLOR_ORANGE_LO        = 7;
var PUSH_COLOR_ORANGE_LO_SBLINK = 8;
var PUSH_COLOR_ORANGE_LO_FBLINK = 9;
var PUSH_COLOR_ORANGE_HI        = 10;
var PUSH_COLOR_ORANGE_HI_SBLINK = 11;
var PUSH_COLOR_ORANGE_HI_FBLINK = 12;
var PUSH_COLOR_YELLOW_LO        = 13;
var PUSH_COLOR_YELLOW_LO_SBLINK = 14;
var PUSH_COLOR_YELLOW_LO_FBLINK = 15;
var PUSH_COLOR_YELLOW_MD        = 16;
var PUSH_COLOR_YELLOW_MD_SBLINK = 17;
var PUSH_COLOR_YELLOW_MD_FBLINK = 18;
var PUSH_COLOR_GREEN_LO         = 19;
var PUSH_COLOR_GREEN_LO_SBLINK  = 20;
var PUSH_COLOR_GREEN_LO_FBLINK  = 21;
var PUSH_COLOR_GREEN_HI         = 22;
var PUSH_COLOR_GREEN_HI_SBLINK  = 23;
var PUSH_COLOR_GREEN_HI_FBLINK  = 24;

// Second row & Pad button colors
var PUSH_COLOR2_BLACK               = 0;
var PUSH_COLOR2_GREY_LO             = 1;
var PUSH_COLOR2_GREY_MD             = 2;
var PUSH_COLOR2_WHITE               = 3;
var PUSH_COLOR2_ROSE                = 4;
var PUSH_COLOR2_RED_HI              = 5;
var PUSH_COLOR2_RED                 = 6;
var PUSH_COLOR2_RED_LO              = 7;
var PUSH_COLOR2_RED_AMBER           = 8;
var PUSH_COLOR2_AMBER_HI            = 9;
var PUSH_COLOR2_AMBER               = 10;
var PUSH_COLOR2_AMBER_LO            = 11;
var PUSH_COLOR2_AMBER_YELLOW        = 12;
var PUSH_COLOR2_YELLOW_HI           = 13;
var PUSH_COLOR2_YELLOW              = 14;
var PUSH_COLOR2_YELLOW_LO           = 15;
var PUSH_COLOR2_YELLOW_LIME         = 16;
var PUSH_COLOR2_LIME_HI             = 17;
var PUSH_COLOR2_LIME                = 18;
var PUSH_COLOR2_LIME_LO             = 19;
var PUSH_COLOR2_LIME_GREEN          = 20;
var PUSH_COLOR2_GREEN_HI            = 21;
var PUSH_COLOR2_GREEN               = 22;
var PUSH_COLOR2_GREEN_LO            = 23;
var PUSH_COLOR2_GREEN_SPRING        = 24;
var PUSH_COLOR2_SPRING_HI           = 25;
var PUSH_COLOR2_SPRING              = 26;
var PUSH_COLOR2_SPRING_LO           = 27;
var PUSH_COLOR2_SPRING_TURQUOISE    = 28;
var PUSH_COLOR2_TURQUOISE_LO        = 29;
var PUSH_COLOR2_TURQUOISE           = 30;
var PUSH_COLOR2_TURQUOISE_HI        = 31;
var PUSH_COLOR2_TURQUOISE_CYAN      = 32;
var PUSH_COLOR2_CYAN_HI             = 33;
var PUSH_COLOR2_CYAN                = 34;
var PUSH_COLOR2_CYAN_LO             = 35;
var PUSH_COLOR2_CYAN_SKY            = 36;
var PUSH_COLOR2_SKY_HI              = 37;
var PUSH_COLOR2_SKY                 = 38;
var PUSH_COLOR2_SKY_LO              = 39;
var PUSH_COLOR2_SKY_OCEAN           = 40;
var PUSH_COLOR2_OCEAN_HI            = 41;
var PUSH_COLOR2_OCEAN               = 42;
var PUSH_COLOR2_OCEAN_LO            = 43;
var PUSH_COLOR2_OCEAN_BLUE          = 44;
var PUSH_COLOR2_BLUE_HI             = 45;
var PUSH_COLOR2_BLUE                = 46;
var PUSH_COLOR2_BLUE_LO             = 47;
var PUSH_COLOR2_BLUE_ORCHID         = 48;
var PUSH_COLOR2_ORCHID_HI           = 49;
var PUSH_COLOR2_ORCHID              = 50;
var PUSH_COLOR2_ORCHID_LO           = 51;
var PUSH_COLOR2_ORCHID_MAGENTA      = 52;
var PUSH_COLOR2_MAGENTA_HI          = 53;
var PUSH_COLOR2_MAGENTA             = 54;
var PUSH_COLOR2_MAGENTA_LO          = 55;
var PUSH_COLOR2_MAGENTA_PINK        = 56;
var PUSH_COLOR2_PINK_HI             = 57;
var PUSH_COLOR2_PINK                = 58;
var PUSH_COLOR2_PINK_LO             = 59;

// Scene button colors
var PUSH_COLOR_SCENE_RED                  = 1;
var PUSH_COLOR_SCENE_RED_BLINK            = 2;
var PUSH_COLOR_SCENE_RED_BLINK_FAST       = 3;
var PUSH_COLOR_SCENE_RED_HI               = 4;
var PUSH_COLOR_SCENE_RED_HI_BLINK         = 5;
var PUSH_COLOR_SCENE_RED_HI_BLINK_FAST    = 6;
var PUSH_COLOR_SCENE_ORANGE               = 7;
var PUSH_COLOR_SCENE_ORANGE_BLINK         = 8;
var PUSH_COLOR_SCENE_ORANGE_BLINK_FAST    = 9;
var PUSH_COLOR_SCENE_ORANGE_HI            = 10;
var PUSH_COLOR_SCENE_ORANGE_HI_BLINK      = 11;
var PUSH_COLOR_SCENE_ORANGE_HI_BLINK_FAST = 12;
var PUSH_COLOR_SCENE_YELLOW               = 13;
var PUSH_COLOR_SCENE_YELLOW_BLINK         = 14;
var PUSH_COLOR_SCENE_YELLOW_BLINK_FAST    = 15;
var PUSH_COLOR_SCENE_YELLOW_HI            = 16;
var PUSH_COLOR_SCENE_YELLOW_HI_BLINK      = 17;
var PUSH_COLOR_SCENE_YELLOW_HI_BLINK_FAST = 18;
var PUSH_COLOR_SCENE_GREEN                = 19;
var PUSH_COLOR_SCENE_GREEN_BLINK          = 20;
var PUSH_COLOR_SCENE_GREEN_BLINK_FAST     = 21;
var PUSH_COLOR_SCENE_GREEN_HI             = 22;
var PUSH_COLOR_SCENE_GREEN_HI_BLINK       = 23;
var PUSH_COLOR_SCENE_GREEN_HI_BLINK_FAST  = 24;
